import fs from "node:fs";
import path from "node:path";
import puppeteer from "puppeteer";
import { buildReportDocumentFromAudit } from "./reportDocument.service.js";
import { renderReport, renderReportForPdf } from "./premiumReportRenderer.service.js";

const STORAGE_ROOT = process.env.PDF_STORAGE_DIR || "storage/pdf-reports";

const ensureStorageDir = async () => {
  const absoluteDir = path.resolve(process.cwd(), STORAGE_ROOT);
  await fs.promises.mkdir(absoluteDir, { recursive: true });
  return absoluteDir;
};

const buildFooterTemplate = (companyName) => {
  const name = companyName || "Ad Adviser";
  return `<div style="width:100%;font-family:Helvetica,Arial,sans-serif;font-size:8px;color:#9ca3af;text-align:center;padding-top:4px;">Generated by ${name} &bull; Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>`;
};

const renderPdfBuffer = async (html, branding = {}) => {
  const executablePath = process.env.PUPPETEER_EXECUTABLE_PATH || undefined;
  const browser = await puppeteer.launch({
    headless: true,
    executablePath,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    await page.evaluateHandle("document.fonts.ready");
    return await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "28px", bottom: "36px", left: "0", right: "0" },
      displayHeaderFooter: true,
      headerTemplate: "<div></div>",
      footerTemplate: buildFooterTemplate(branding.companyName),
    });
  } finally {
    await browser.close();
  }
};

export const generateAuditPdfFile = async ({ audit, version, branding = {} }) => {
  const storageDir = await ensureStorageDir();
  const fileName = `audit-${audit.id}-v${version}.pdf`;
  const htmlFileName = `audit-${audit.id}-v${version}.html`;
  const absolutePath = path.join(storageDir, fileName);
  const absoluteHtmlPath = path.join(storageDir, htmlFileName);
  const relativePath = path.relative(process.cwd(), absolutePath);
  const reportDocument = buildReportDocumentFromAudit(audit);

  await fs.promises.writeFile(absoluteHtmlPath, renderReport(reportDocument, branding), "utf8");

  const pdfBuffer = await renderPdfBuffer(renderReportForPdf(reportDocument, branding), branding);
  await fs.promises.writeFile(absolutePath, pdfBuffer);

  return {
    storagePath: relativePath,
    absolutePath,
    htmlPath: path.relative(process.cwd(), absoluteHtmlPath),
    absoluteHtmlPath,
  };
};

export const resolveStoredPdfPath = (storagePath) =>
  path.resolve(process.cwd(), storagePath);
